name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fms:
    path: "../../fms"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MySymbols
      fonts:
        - asset: assets/my_symbols.ttf
