name: fms
description: Brings Google's Material symbols to your flutter project.
version: 0.9.0
repository: https://github.com/fujidaiti/fms.git

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  cli_util: ^0.3.5
  collection: ^1.16.0
  fpdart: ^0.4.0
  icon_font_generator: ^3.2.0
  internet_file: ^1.2.0
  meta: ^1.8.0
  path: ^1.8.2
  recase: ^4.1.0
  source_span: ^1.9.0
  yaml: ^3.1.1
