// GENERATED AT 2023-01-08 01:12:48.618603
// BASED ON THE COMMIT 511eea577b20d2b02ad77477750da1e44c66a52c

class RepositoryInfo {
  final String baseUrl;
  final Set<String> availableSymbolNames;
  const RepositoryInfo._({
    required this.baseUrl,
    required this.availableSymbolNames,
  });
}

const repositoryInfo = RepositoryInfo._(
  baseUrl:
      'https://raw.githubusercontent.com/google/material-design-icons/511eea577b20d2b02ad77477750da1e44c66a52c/symbols/web',
  availableSymbolNames: {
    'Enable',
    '3k',
    'Nest Cam Floodlight',
    'Device Unknown',
    'Air Freshener',
    'Weight',
    'Sign Language',
    'Gavel',
    'Line Start Square',
    'Folder Shared',
    'Youtube Activity',
    'Cameraswitch',
    'Oral Disease',
    'Agriculture',
    'Decimal Increase',
    'Diamond',
    'Humidity Mid',
    'Skull',
    'Local Library',
    'Brightness 4',
    'Indeterminate Check Box',
    'Auto Fix High',
    'Nest Hello Doorbell',
    'Add Shopping Cart',
    'Broken Image',
    'Line Start Diamond',
    'Token',
    'Swipe Down',
    'Music Video',
    'Child Care',
    'Shopping Bag',
    'Flashlight Off',
    'Google Wifi',
    'Edit Square',
    'Quick Phrases',
    'Biotech',
    'Wind Power',
    'Brightness 3',
    'Nest Mini',
    'Connecting Airports',
    'Qr Code Scanner',
    'Traffic',
    'New Releases',
    'Sports Cricket',
    'Assistant',
    'Aod Tablet',
    'Pause',
    'Webhook',
    'Crisis Alert',
    'Arrow Forward',
    'Format Underlined Squiggle',
    'Lyrics',
    'Bakery Dining',
    'Sports Tennis',
    'Man',
    'Playlist Add',
    'Outbox',
    'Alternate Email',
    'Signpost',
    'Tibia',
    'Departure Board',
    'Grid Off',
    'Familiar Face And Zone',
    'Glyphs',
    'Nest Clock Farsight Analog',
    'Fire Hydrant',
    'Tools Level',
    'Phone Callback',
    'Commit',
    'Monochrome Photos',
    'Recycling',
    'Vibration',
    'Density Large',
    'Microwave',
    'Phone Paused',
    'Flip Camera Ios',
    'Vitals',
    'Hand Gesture',
    'U Turn Right',
    'Gradient',
    'Control Camera',
    'Search Off',
    'Data Array',
    'Sports Score',
    'Forest',
    'Switch Camera',
    'Power',
    'Battery 3 Bar',
    'Inpatient',
    'Subdirectory Arrow Right',
    '4g Plus Mobiledata',
    'Bluetooth Searching',
    'Move Down',
    'Remove Shopping Cart',
    'Wifi Channel',
    'Nightlight',
    'Directions Walk',
    'Wifi',
    'Rss Feed',
    'Arrow Insert',
    'Airline Seat Recline Extra',
    'Wrong Location',
    'Keyboard Capslock',
    'Snippet Folder',
    'Timer 3 Alt 1',
    'Battery 2 Bar',
    'Labs',
    'Sms Failed',
    'Calendar Apps Script',
    'Heat Pump Balance',
    'Signal Wifi Statusbar Null',
    'Meeting Room',
    '3p',
    'Help Clinic',
    'Add Road',
    'Dashboard Customize',
    'Insights',
    'Shield',
    'Sports Rugby',
    'Cancel',
    'Hearing',
    'Airline Seat Legroom Normal',
    'Temp Preferences Eco',
    'Not Listed Location',
    'Note',
    'Discover Tune',
    'Format Paint',
    'Swap Horiz',
    'Attractions',
    'Wifi Tethering Off',
    'Magnification Small',
    'Share Location',
    'Phone Enabled',
    'Monetization On',
    'Draft',
    'Rib Cage',
    'Brunch Dining',
    'Cake Add',
    'Swipe Vertical',
    'Join Inner',
    'Settings Applications',
    'Cloudy',
    'Water Ph',
    'Handyman',
    'Mode Cool Off',
    'Water Drop',
    'Settings',
    'Home',
    'Tools Installation Kit',
    'Database',
    'Video Library',
    'Vrpano',
    '5g',
    'Thumb Down',
    'Incomplete Circle',
    'Two Wheeler',
    'Add Location',
    'Surround Sound',
    'Trending Up',
    'Home Mini',
    'Luggage',
    'Window Closed',
    'Cell Merge',
    'App Registration',
    'Sick',
    'Cell Tower',
    'Body Fat',
    'Auto Fix Off',
    'Signal Wifi Statusbar Not Connected',
    'History Edu',
    'Signal Wifi Off',
    'Lift To Talk',
    'Abc',
    'Person Search',
    'Electric Scooter',
    'Swipe Left Alt',
    'Repeat',
    '9k',
    'Fluorescent',
    'Plagiarism',
    'Home Max Dots',
    'Sports Handball',
    'Surfing',
    'Format Underlined',
    'Sd',
    'Restart Alt',
    'Expand Less',
    'Turn Sharp Left',
    'Decimal Decrease',
    'Fireplace',
    'Cottage',
    'South America',
    'App Blocking',
    'Vertical Distribute',
    'Mode Fan Off',
    'Blind',
    'Beach Access',
    'Sensors',
    'Fit Screen',
    'Fmd Bad',
    'Restaurant',
    'Dry',
    'Sports Hockey',
    'Line End Square',
    'Format Italic',
    'Play Pause',
    'Sell',
    '23mp',
    'Tablet',
    'Reorder',
    'Piano',
    'View Stream',
    'Woman 2',
    'Group Remove',
    'Compress',
    'Cleaning Services',
    'Tire Repair',
    'Ring Volume',
    'Build Circle',
    'Flag',
    'Join Full',
    'Key Visualizer',
    'Home App Logo',
    'Sensor Door',
    'Speech To Text',
    'Fastfood',
    'Cooking',
    'Flag Circle',
    'Local Laundry Service',
    'Import Contacts',
    'Video Camera Front',
    'Approval Delegation',
    'Save As',
    'Medical Services',
    'Noise Control On',
    'Cloudy Filled',
    'View Comfy',
    'Disabled By Default',
    'Brightness 2',
    'Directions',
    'Nest Doorbell Visitor',
    'Garden Cart',
    'Font Download',
    'Settings Accessibility',
    'Public Off',
    'Audio File',
    'Gpp Maybe',
    'Location Disabled',
    'G Translate',
    'Brightness 5',
    'Water Damage',
    'Gas Meter',
    'View Module',
    'Blanket',
    '2k Plus',
    'Battery 0 Bar',
    'Tsunami',
    'Leak Remove',
    'Format List Bulleted',
    'Payments',
    'Burst Mode',
    'Transportation',
    'File Upload',
    'Create New Folder',
    'Arrow Drop Down',
    'View List',
    'Battery 1 Bar',
    'Blinds',
    'Location Automation',
    'Settings Phone',
    'Photo Frame',
    'Credit Card',
    'Contactless',
    'Format Shapes',
    'Folder Open',
    'Edit Location',
    'Roundabout Left',
    'Toc',
    'Detector Smoke',
    'Picture As Pdf',
    'Keyboard Double Arrow Left',
    'Videocam',
    'Movie',
    'Reset Image',
    'Local Shipping',
    'Exposure',
    'Clear Day',
    'Mail Lock',
    'Hdr Auto',
    'Thumb Down Off',
    'Copy All',
    'Fire Extinguisher',
    'Component Exchange',
    'Select Check Box',
    'Keyboard Double Arrow Right',
    'Library Music',
    'Brightness High',
    'Upgrade',
    'Expand',
    'List Alt',
    'Vape Free',
    'Signal Cellular Nodata',
    'Keyboard Hide',
    'Format Text Overflow',
    'Person Off',
    'Rv Hookup',
    'Drag Indicator',
    'Stay Primary Portrait',
    'Balcony',
    'Arrow Downward',
    'Font Download Off',
    'Sports Volleyball',
    'Event Repeat',
    'Remove',
    'Schedule',
    'Filter Tilt Shift',
    '10k',
    'Screenshot',
    'Oven Gen',
    'Egg',
    'Turn Right',
    'Settings Photo Camera',
    'Enhanced Encryption',
    'Unfold Less',
    'Fiber Manual Record',
    'Password',
    'Add Comment',
    'Shuffle',
    'Adjust',
    'Tap And Play',
    'Search Check',
    'Remove Road',
    'Domain Add',
    'Task Alt',
    'Camera Rear',
    'Pin',
    'Contact Support',
    'Auto Awesome',
    'Add Business',
    'Weather Snowy',
    'Drive File Move Rtl',
    'Forms Apps Script',
    'Pregnant Woman',
    'Tty',
    'Auto Fix',
    'Reduce Capacity',
    'Bed',
    'Google Plus Reshare',
    'Monitor',
    'Tab Unselected',
    'Border Bottom',
    'Nest Thermostat Sensor',
    'Electric Bike',
    'Raw Off',
    'Hardware',
    'Room Service',
    'Drive File Move',
    'Dynamic Feed',
    'Car Crash',
    'Auto Detect Voice',
    'Select All',
    'Battery Full',
    'Roller Shades Closed',
    'Do Not Touch',
    'Storefront',
    'Phone Locked',
    'Post Add',
    'Content Copy',
    'Hdr On Select',
    'Radio Button Unchecked',
    'Music Off',
    'Photo Library',
    'Escalator',
    'Do Not Disturb On',
    'Laundry',
    'Man 2',
    'Salinity',
    'Check Box Outline Blank',
    'Cloud Done',
    'Star Rate',
    'Published With Changes',
    'Door Back',
    'Grading',
    'Lightbulb Circle',
    'Numbers',
    'Transfer Within A Station',
    'Perm Data Setting',
    'Smoking Rooms',
    'Countertops',
    'No Transfer',
    'Signal Cellular Alt 1 Bar',
    'Radio',
    'Pageview',
    'Edit Document',
    'Cinematic Blur',
    'Do Not Disturb On Total Silence',
    'Bookmark',
    'Wb Sunny',
    'Hdr Auto Select',
    'Cloud Queue',
    'Inbox',
    'Battery 5 Bar',
    'Check Circle',
    'Battery 4 Bar',
    'Pin End',
    'Scale',
    'File Present',
    'Savings',
    '16mp',
    'Close',
    'Desktop Mac',
    'Folder Copy',
    'Replay Circle Filled',
    'Location Searching',
    'Expand Content',
    'Fingerprint',
    'Tools Power Drill',
    'Local Activity',
    'Diversity 1',
    'Nest Remote',
    '6 Ft Apart',
    'Calendar View Month',
    'Trolley',
    'Extension',
    'Credit Card Off',
    'Visibility Off',
    'Rowing',
    'Last Page',
    'Mark Chat Unread',
    'North',
    'Flash Auto',
    'Privacy',
    'Desk',
    '3mp',
    'Crop 16 9',
    'Stroller',
    'Alarm On',
    '6k Plus',
    'Vertical Split',
    'Memory',
    'Propane Tank',
    'Add Alert',
    'Pivot Table Chart',
    'Flight Class',
    'Usb Off',
    'High Quality',
    'Remove From Queue',
    'Settings Brightness',
    'Settings Input Svideo',
    'Spoke',
    'Mode Comment',
    'Table Chart',
    'Weekend',
    'Design Services',
    'Mode Heat Off',
    'Drive File Rename Outline',
    'Infrared',
    '9mp',
    'Layers',
    'Bedtime Off',
    'Calendar Add On',
    'Detection And Zone',
    'Currency Franc',
    'Draft Orders',
    'Rebase Edit',
    'Crop Rotate',
    'Unknown Med',
    'Inventory 2',
    'Wine Bar',
    'Push Pin',
    'Motion Photos Paused',
    'Sports Bar',
    'Blur Off',
    'Format Color Reset',
    'No Crash',
    'Fact Check',
    'Route',
    '18mp',
    'Camera Front',
    'Join',
    'Calculate',
    'Settings Input Antenna',
    'Not Started',
    'Home Health',
    'Man 4',
    'Filter None',
    'Monitor Weight',
    'All Inclusive',
    'Hdr Weak',
    'Electric Meter',
    '4k Plus',
    'Share Reviews',
    'Group Add',
    'Business Center',
    'Contact Page',
    'Align Horizontal Left',
    'Man 3',
    'Border Vertical',
    'Archive',
    'Party Mode',
    'Chromecast Device',
    'Filter Vintage',
    'Boy',
    'Settings Voice',
    'Update',
    'Drive File Move Outline',
    'Time Auto',
    'Category',
    'Chat',
    'Subscript',
    'App Shortcut',
    'Dark Mode',
    'Fork Left',
    'Mobile Screen Share',
    'Looks 6',
    'Keyboard Arrow Left',
    'Door Front',
    'Bar Chart',
    'Settop Component',
    'Leak Add',
    'Breastfeeding',
    'Label Off',
    'Real Estate Agent',
    'Unfold Less Double',
    'Sort',
    'Headset Off',
    'House Siding',
    'Notification Important',
    '12mp',
    'Power Off',
    'Nest True Radiant',
    'Stethoscope',
    'Waving Hand',
    'Mark Email Read',
    'Type Specimen',
    'Water',
    'Shutter Speed',
    'No Adult Content',
    'Hd',
    '7mp',
    'Signal Cellular Alt 2 Bar',
    'Timer 10 Select',
    'Delete',
    'Turn Left',
    'Filter Center Focus',
    'Nest Wifi Point',
    'View Column',
    'Arrow Drop Up',
    'Offline Bolt',
    'Battery 6 Bar',
    'Replay 5',
    'Car Rental',
    'Femur',
    'Exposure Neg 1',
    'View Array',
    'Sim Card',
    'Equalizer',
    'Sheets Rtl',
    'Camping',
    'Perm Contact Calendar',
    'Carpenter',
    'Unpublished',
    'Assist Walker',
    'How To Vote',
    'Pulmonology',
    'Pie Chart',
    'Exposure Plus 1',
    'Hotel',
    'How To Reg',
    'Download Done',
    'Photo Filter',
    'Recommend',
    'Brightness Low',
    'Nest Cam Wired Stand',
    'Emoji Symbols',
    'Garage Home',
    'Qr Code 2',
    'Toys',
    'Voice Chat',
    'Swipe Up',
    'Visibility',
    'Note Add',
    'Lock Person',
    'Face',
    'Verified',
    'Battery Saver',
    'Airline Seat Legroom Reduced',
    'Playlist Add Circle',
    'Emergency Share',
    'Blinds Closed',
    'Css',
    'Dinner Dining',
    'Lunch Dining',
    'Today',
    'Turn Slight Left',
    'Join Right',
    'Motion Sensor Active',
    'Volume Down',
    'Data Thresholding',
    'Hevc',
    'Slow Motion Video',
    'Merge',
    'Nest Display Max',
    'Roundabout Right',
    'Rtt',
    'More Down',
    'Manage Accounts',
    'Sms',
    'Price Change',
    'Bolt',
    'Fiber Pin',
    'Play Disabled',
    'Add Chart',
    'Subtitles Off',
    'Pinch Zoom Out',
    'Timer 3',
    'Settings Suggest',
    'Solar Power',
    'Playlist Remove',
    'Ramen Dining',
    'Fullscreen Exit',
    'Gite',
    'Nest Remote Comfort Sensor',
    'Image Not Supported',
    'Lock Reset',
    'Stacked Line Chart',
    'Security',
    'Change Circle',
    'Notifications Paused',
    'Flaky',
    'Title',
    'Photo Camera Back',
    'Speaker',
    'Smartphone',
    'Candlestick Chart',
    'Translate',
    'Climate Mini Split',
    'Filter Frames',
    'Align Horizontal Right',
    'Star Rate Half',
    'Settings Ethernet',
    'Lock Open',
    'Gallery Thumbnail',
    'Line End Arrow Notch',
    'Bedroom Child',
    'Highlight',
    'Keyboard Voice',
    'Align Vertical Center',
    'Content Cut',
    'Input',
    'Fax',
    'Library Add',
    'Content Paste Go',
    'Dehaze',
    'Edit Location Alt',
    'Format Textdirection L To R',
    'Line End Arrow',
    '3k Plus',
    'Group',
    'Missed Video Call',
    'Settings Cell',
    'Explicit',
    'Face 3',
    'Sd Card',
    'Hide Source',
    'Forward To Inbox',
    'Keyboard Command Key',
    'Charger',
    'Short Stay',
    '4g Mobiledata',
    'Settings Bluetooth',
    'Trending Flat',
    'Groups 3',
    'Night Sight Auto Off',
    'Directions Alt Off',
    'Face 4',
    'Person',
    'Tools Phillips',
    'Skateboarding',
    'Taxi Alert',
    'Sunny',
    'Contact Phone',
    'Domain Disabled',
    'Bathroom',
    'Cast',
    'Note Alt',
    'Mode Heat',
    'Subdirectory Arrow Left',
    'Crop 5 4',
    'Bedroom Baby',
    'Escalator Warning',
    'Redo',
    'Swap Vertical Circle',
    'Filter List',
    'Chart Data',
    'Manage Search',
    'Star Half',
    'Sports Golf',
    'Refresh',
    'Filter Drama',
    'Brightness Auto',
    'Sync Problem',
    'Featured Video',
    'Soup Kitchen',
    'Comment',
    'Folder Delete',
    'Local Pizza',
    'Grass',
    'Pets',
    'Speed',
    'Currency Rupee',
    'Border Clear',
    'Sort By Alpha',
    'Mail',
    'Bike Scooter',
    'Atm',
    'Text Snippet',
    '24mp',
    'Assignment Ind',
    'Event Upcoming',
    'Golf Course',
    'Radio Button Checked',
    'Cloud Download',
    'Lab Panel',
    'Tenancy',
    'Set Meal',
    'Folder Special',
    'Hide Image',
    'Network Ping',
    'Living',
    'Barcode Reader',
    'Phonelink Off',
    'Format Text Wrap',
    'Web',
    'Takeout Dining',
    'Raw On',
    'Flashlight On',
    'Network Locked',
    'File Download Off',
    'Auto Activity Zone',
    'Doorbell',
    'Airplanemode Active',
    'Nest Wifi Point Vento',
    'Screen Rotation Alt',
    'Panorama Photosphere',
    'Skeleton',
    'Shelves',
    'Replay 10',
    'Dataset',
    'Humidity Low',
    'Apps Outage',
    'Nest Thermostat Sensor Eu',
    'Arrow Circle Down',
    'Phone Android',
    'Table Lamp',
    'Camera',
    'Stay Current Portrait',
    'Line Axis',
    'Supervisor Account',
    'Polyline',
    'Minor Crash',
    'Grid Goldenratio',
    'Maps Ugc',
    'Flood',
    'Deblur',
    'Wb Auto',
    'Safety Divider',
    'Clarify',
    'Developer Board Off',
    'Park',
    'Rheumatology',
    'Cleaning Bucket',
    'Nest Wifi Gale',
    'Filter 5',
    'Conversion Path',
    'Height',
    'Tablet Android',
    'Text Rotate Vertical',
    'System Update',
    'File Open',
    'Nest Cam Magnet Mount',
    'Pest Control',
    'Attachment',
    'Format Quote',
    'Drafts',
    'Key Off',
    'Code Blocks',
    'Directions Boat',
    'Emoji People',
    'Filter 2',
    'Picture In Picture Alt',
    'Thermometer',
    'Face Retouching Natural',
    'Link Off',
    'Valve',
    'Filter B And W',
    'Work History',
    'Content Paste',
    'Shop Two',
    'Finance Chip',
    'Range Hood',
    'Cancel Presentation',
    'Assignment Returned',
    'Add Reaction',
    'Repartition',
    'Handshake',
    'Horizontal Distribute',
    'Battery Charging 30',
    'Wysiwyg',
    'Light Mode',
    'Pin Invoke',
    'Vertical Align Top',
    'Routine',
    'Square',
    'System Update Alt',
    'Align Vertical Top',
    'Cloud Upload',
    'Format List Numbered',
    'Door Sensor',
    'Hdr Enhanced Select',
    'Expand More',
    'Network Wifi',
    'Mark Unread Chat Alt',
    'Nat',
    'Contacts',
    'Electric Bolt',
    'Play Arrow',
    'Flight',
    'Phonelink Ring',
    'Format Color Fill',
    'Other Admission',
    'Empty Dashboard',
    '60fps Select',
    'Cycle',
    'Stream',
    'Magnification Large',
    'Picture In Picture',
    'Compare Arrows',
    'Nest Audio',
    'Casino',
    'Chat Bubble',
    'Groups 2',
    'Sports Martial Arts',
    'Tamper Detection On',
    'Forward 5',
    'Face 5',
    'Group Off',
    'Pedal Bike',
    'Perm Device Information',
    'Dishwasher Gen',
    'Desktop Access Disabled',
    'Motion Blur',
    'Thermostat Auto',
    'Data Usage',
    'Footprint',
    'Face 2',
    'Directions Bike',
    'Folder',
    'R Mobiledata',
    'Lda',
    'Moving',
    'Space Dashboard',
    'Chat Apps Script',
    'Signal Cellular 4 Bar',
    'Power Input',
    'Fire Truck',
    'File Download Done',
    'Directions Run',
    'Psychology',
    'Mark Chat Read',
    'Control Point Duplicate',
    'Queue Play Next',
    'Density Small',
    'Arrow Outward',
    'Pending Actions',
    'Bubble Chart',
    'Segment',
    'View Comfy Alt',
    'Arrow Drop Down Circle',
    'Activity Zone',
    'Local Car Wash',
    'Add Home',
    'Settings Overscan',
    'Tv Off',
    'Open In Full',
    'Theaters',
    'Spatial Audio',
    'Stethoscope Check',
    'Settings Remote',
    'Filter 3',
    'Conveyor Belt',
    'Swap Vert',
    'Timer',
    'Church',
    'Wb Incandescent',
    'Shop',
    'Oil Barrel',
    'Straighten',
    'Volume Off',
    'Vertical Align Center',
    'Calendar View Day',
    '20mp',
    'Interpreter Mode',
    'Filter 4',
    'Amp Stories',
    'Elderly',
    'Signal Cellular Null',
    'Percent',
    'My Location',
    'Tapas',
    'Settings System Daydream',
    'Orthopedics',
    'Screen Lock Portrait',
    'Thumb Up',
    'Flip To Front',
    'Straight',
    'Panorama Fish Eye',
    'Forklift',
    'Subject',
    'Slide Library',
    'Live Help',
    '1k Plus',
    'Keyboard Alt',
    'Drag Handle',
    'Battery Charging 90',
    'Science',
    'Turn Slight Right',
    'Radiology',
    'Signal Disconnected',
    'Problem',
    'Charging Station',
    'Flip To Back',
    'Border Left',
    'Ulna Radius Alt',
    'Airline Seat Individual Suite',
    'Railway Alert',
    'Zoom In Map',
    'Laptop Windows',
    'Security Update Good',
    'Unfold More',
    'Local Gas Station',
    'Video Camera Front Off',
    'Crop',
    'Closed Caption',
    'Auto Graph',
    'Mode Heat Cool',
    'Timelapse',
    'Wifi 1 Bar',
    'Wifi Calling 1',
    'Breaking News Alt 1',
    'Spatial Audio Off',
    'Hdr Off Select',
    'Sensors Off',
    'Graphic Eq',
    'Stay Primary Landscape',
    'Coffee Maker',
    'Format Indent Decrease',
    'Speaker Group',
    'Sanitizer',
    '30fps Select',
    '15mp',
    'Transit Enterexit',
    'Add Home Work',
    'Done Outline',
    'Summarize',
    'Contact Mail',
    'Clinical Notes',
    'Smoke Free',
    'Lock',
    'Offline Share',
    'Outpatient',
    'Live Tv',
    'Flash Off',
    'Directions Alt',
    'Output',
    'Single Bed',
    'Check Indeterminate Small',
    '4k',
    'Auto Stories',
    'Motorcycle',
    'Video File',
    'Humerus',
    'Read More',
    'Nest Wifi Router',
    'Code',
    'Navigation',
    'Videocam Off',
    'Wc',
    'Cases',
    'Playlist Add Check',
    'Stars',
    'Label',
    'Pentagon',
    'Settings Backup Restore',
    'Mode Fan',
    'Quiz',
    'Chair',
    'View Quilt',
    'Vpn Lock',
    'Cloud Circle',
    'Local See',
    'Hls Off',
    'Currency Exchange',
    'Format H1',
    'Hail',
    'Arrow Forward Ios',
    'Start',
    'Grid On',
    'Redeem',
    'Frame Person',
    'Polymer',
    'Aod',
    'Home Max',
    'Format Align Left',
    'Format Overline',
    'Emergency',
    'Library Books',
    'Animation',
    'Signal Cellular 1 Bar',
    'Saved Search',
    'Nest Clock Farsight Digital',
    'Format H6',
    'Phone Disabled',
    'Mic',
    'Back Hand',
    'Whatshot',
    'Foundation',
    'Download For Offline',
    'Terminal',
    '5k Plus',
    'Find Replace',
    'Forward 10',
    'Curtains',
    'Event Seat',
    'Screen Rotation',
    'Self Improvement',
    'Flip',
    'Signal Cellular 0 Bar',
    'Sim Card Download',
    'No Stroller',
    'Spellcheck',
    'Headphones',
    'Details',
    'Hvac',
    'H Plus Mobiledata',
    'Unfold More Double',
    'Battery Horiz 000',
    'Format Align Justify',
    'Video Camera Back',
    'Account Tree',
    'Wifi Protected Setup',
    'Stadium',
    'Nest Display',
    'Docs Apps Script',
    'Tv With Assistant',
    'Dresser',
    'Piano Off',
    'Security Update Warning',
    'Balance',
    'Stop Circle',
    'View Timeline',
    'Media Bluetooth On',
    'Stop',
    'Swipe',
    'Admin Panel Settings',
    'Corporate Fare',
    'Curtains Closed',
    'Assignment',
    'Sentiment Very Dissatisfied',
    'Add A Photo',
    'Mobile Friendly',
    'Detector Status',
    'Code Off',
    'Phone In Talk',
    'Edgesensor Low',
    'Flutter Dash',
    'View Compact Alt',
    'Matter',
    'View In Ar',
    'Logout',
    'Favorite',
    'Roller Skating',
    'Video Chat',
    'Cloud Sync',
    'Shapes',
    'Process Chart',
    'Html',
    'Install Desktop',
    'Keyboard Return',
    'Language',
    'No Drinks',
    'Tram',
    'Cached',
    'Style',
    'Label Important',
    'Thermostat Carbon',
    'Scuba Diving',
    'Potted Plant',
    'Leaderboard',
    'Nest Cam Outdoor',
    'Family Restroom',
    'Nest Farsight Weather',
    'Groups',
    'Wifi 2 Bar',
    'Format Indent Increase',
    'Deselect',
    'Battery 30',
    'Checkroom',
    'Key',
    'Battery Charging Full',
    'Local Florist',
    'Newspaper',
    'Edgesensor High',
    'Hexagon',
    '18 Up Rating',
    'Markunread Mailbox',
    'Sports Mma',
    'Humerus Alt',
    'Repeat One',
    'Topic',
    'Thumbs Up Down',
    'Horizontal Split',
    'Arrow Right Alt',
    'Severe Cold',
    'Loyalty',
    'Currency Ruble',
    'Tibia Alt',
    'Bug Report',
    'Phonelink Erase',
    'Settings Account Box',
    'Call To Action',
    'Pan Tool',
    'Compass Calibration',
    'Edit Calendar',
    'Add Card',
    'Local Atm',
    'Playlist Play',
    'Autorenew',
    'Toggle On',
    'Assignment Late',
    'Air',
    'Function',
    'Undo',
    'Shield With House',
    'Crop Square',
    'Nest Connect',
    '7k',
    'Nature',
    'Local Drink',
    'Tab',
    'Partly Cloudy Day',
    'Shape Line',
    'Unsubscribe',
    'Motion Sensor Urgent',
    'Done All',
    'Chat Add On',
    'Signal Cellular 2 Bar',
    'Settings Motion Mode',
    'Wifi Find',
    'Soap',
    'Liquor',
    'Airline Seat Flat Angled',
    'Php',
    'Paid',
    'Signal Cellular 3 Bar',
    'Auto Mode',
    'Keyboard Option Key',
    'On Device Training',
    'Houseboat',
    'Workspaces',
    'Emergency Recording',
    'Mediation',
    'Bus Alert',
    'Videogame Asset',
    'Auto Fix Normal',
    'Pinch Zoom In',
    'Restaurant Menu',
    'No Sim',
    'Tv',
    'Ev Charger',
    'Exclamation',
    'Lte Plus Mobiledata',
    'Directions Off',
    '7k Plus',
    'Join Left',
    'Eco',
    'Rate Review',
    'Invert Colors Off',
    'Space Bar',
    'U Turn Left',
    'Screen Share',
    'Roofing',
    'Bluetooth Connected',
    'More Time',
    'Wifi Tethering',
    'Shower',
    'Nest Thermostat Gen 3',
    'Fluid',
    'Print',
    '11mp',
    'Person Add',
    'Content Paste Search',
    'Grade',
    'Night Shelter',
    'Local Fire Department',
    'Filter Hdr',
    'Self Care',
    'Satellite Alt',
    'Print Disabled',
    'Supervised User Circle',
    'Movie Edit',
    'Watch Off',
    'Tools Flat Head',
    'Sports',
    'Robot',
    'Image',
    'Wifi Off',
    'Toys Fan',
    'Battery 90',
    'View Cozy',
    'More',
    'Rule Folder',
    'Add Location Alt',
    'Local Pharmacy',
    '4mp',
    'Storage',
    'Media Bluetooth Off',
    'File Copy',
    'Run Circle',
    'Lte Mobiledata',
    'Podcasts',
    'Partly Cloudy Night',
    'Doorbell 3p',
    'Stay Current Landscape',
    'Edit Note',
    'Toggle Off',
    'Add To Home Screen',
    'Smart Screen',
    'Battery 20',
    'Explore',
    'Auto Schedule',
    'Move Up',
    'Sentiment Very Satisfied',
    'Do Not Step',
    'Rectangle',
    'Hourglass Bottom',
    'Inactive Order',
    'Spa',
    'Splitscreen',
    'Line End Circle',
    'Hide',
    'Crop Landscape',
    'Nest Heat Link E',
    'Rule',
    'Total Dissolved Solids',
    'Chevron Left',
    'Macro Off',
    'Subscriptions',
    'Send And Archive',
    'Monitor Heart',
    'Hotel Class',
    'Search',
    'Fast Rewind',
    'Cabin',
    'Fork Right',
    'Mms',
    'Text Format',
    'Folder Zip',
    'Villa',
    'Perm Media',
    'Mouse',
    'Play Circle',
    'Mood Bad',
    'Unarchive',
    'Chromecast 2',
    'Portable Wifi Off',
    'Bookmark Add',
    'Timer 3 Select',
    'Wounds Injuries',
    'Dirty Lens',
    'Blur Linear',
    'Phone In Talk Watchface Indicator',
    'Downhill Skiing',
    'Location City',
    'Photo Camera Front',
    'Help Center',
    'Perm Scan Wifi',
    'Keyboard Double Arrow Up',
    'East',
    'Home Storage',
    'Mic Off',
    'Switch Video',
    'Legend Toggle',
    '6k',
    'Menu Open',
    'Phone Missed',
    'Spatial Tracking',
    'Info',
    'Dashboard',
    'Where To Vote',
    'Blur Circular',
    'Ios Share',
    'Foot Bones',
    'Format Clear',
    'Trending Down',
    'Swords',
    'Kayaking',
    'Business Chip',
    'Difference',
    'Donut Small',
    'Nest Eco Leaf',
    'Zone Person Idle',
    'Pause Presentation',
    'Usb',
    'Network Check',
    'Scatter Plot',
    'Switch Account',
    'Dialer Sip',
    'Edit',
    'Schema',
    'Reply All',
    'Browser Updated',
    'Outlet',
    'Text Fields',
    'Coronavirus',
    'Flourescent',
    'Landslide',
    'Text Decrease',
    'Play Lesson',
    'Brightness 7',
    'Border Top',
    'Elderly Woman',
    'Forum',
    'Forward 30',
    'Grain',
    'Adb',
    'Reset Tv',
    'Tornado',
    'Warning',
    'Nordic Walking',
    'Fiber New',
    'Tamper Detection Off',
    'Receipt Long',
    'Near Me Disabled',
    'Local Cafe',
    'Hourglass Full',
    'Sentiment Dissatisfied',
    'Nest Locator Tag',
    'Sensor Window',
    'Switch Left',
    'Repeat One On',
    'Astrophotography Off',
    'Star',
    'Outgoing Mail',
    'Pan Tool Alt',
    'Image Aspect Ratio',
    'Medical Information',
    'Battery 80',
    'Mobiledata Off',
    'Zoom Out',
    'Zone Person Urgent',
    'Kettle',
    'Group Work',
    'Reply',
    'Lens',
    'Auto Awesome Motion',
    'Fort',
    'Ac Unit',
    'Nest Cam Wall Mount',
    'Signal Cellular Connected No Internet 0 Bar',
    'Arrow Circle Up',
    'Person Remove',
    'No Food',
    'Line Start Circle',
    'Vital Signs',
    'Outdoor Grill',
    'Format Text Clip',
    'Motion Sensor Alert',
    'Remote Gen',
    'Privacy Tip',
    'Score',
    'Nest Heat Link Gen 3',
    'Bookmark Remove',
    'Nearby Off',
    'Add To Queue',
    'Sunny Snowing',
    'Publish',
    'Architecture',
    'Movie Filter',
    'Room Preferences',
    'Report Off',
    'Directions Car',
    'Voice Over Off',
    'Receipt',
    'Military Tech',
    'Hourglass Disabled',
    'Quickreply',
    'Eject',
    'Phone Forwarded',
    'Timer 10',
    'Tools Wrench',
    'Border Color',
    'Map',
    'Switch Right',
    'Battery Horiz 075',
    'Keyboard Arrow Down',
    'G Mobiledata',
    'Voting Chip',
    'Celebration',
    'Directions Subway',
    'Card Membership',
    'Rotate 90 Degrees Cw',
    'Emoji Nature',
    'Panorama Horizontal',
    'Wb Twilight',
    'No Backpack',
    'Photo Album',
    'Rainy',
    'Volume Down Alt',
    'Verified User',
    'Close Fullscreen',
    'Ulna Radius',
    '5k',
    'Acute',
    'Sailing',
    'Width Wide',
    'Domain Verification',
    'Pacemaker',
    'No Encryption',
    'Public',
    'Ev Station',
    'Call',
    'Tablet Mac',
    'Speaker Phone',
    'Alarm Add',
    'Detector',
    'Mode Night',
    '360',
    'Cool To Dry',
    'Notes',
    'Done',
    'Add',
    'Event Note',
    'Double Arrow',
    'Bookmarks',
    'Nest Cam Indoor',
    'Loupe',
    'Child Friendly',
    'Swipe Right',
    'Imagesmode',
    'Explore Off',
    'Track Changes',
    'Styler',
    'Zoom Out Map',
    'Text Increase',
    'Link',
    'Description',
    '9k Plus',
    'Device Reset',
    'Looks',
    'Short Text',
    'Scoreboard',
    'Background Replace',
    'Connect Without Contact',
    'Devices Fold',
    'Night Sight Auto',
    'Photo Size Select Small',
    'Touch App',
    '60fps',
    'Digital Out Of Home',
    'Brightness 6',
    'Border Outer',
    'Home Work',
    'Hot Tub',
    'Support',
    '21mp',
    'Generating Tokens',
    'Grid 3x3',
    'Opacity',
    'Microwave Gen',
    'Admin Meds',
    'Settings Input Component',
    'Badge Critical Battery',
    'Navigate Next',
    'Book Online',
    'Attach Email',
    'Download',
    'Dew Point',
    'Thermostat',
    'Table',
    'Dynamic Form',
    'Lock Clock',
    'Trail Length Short',
    'Brightness 1',
    'Cable',
    'Sound Detection Dog Barking',
    'Wall Lamp',
    'Speaker Notes Off',
    'Alt Route',
    'Battery Charging 20',
    'Magic Button',
    'Synagogue',
    'Water Do',
    'Add Circle',
    'King Bed',
    'Http',
    'Thumb Up Off',
    'Shopping Cart Checkout',
    'Format Align Right',
    'Dangerous',
    'Format Color Text',
    'Airplay',
    'Add Box',
    'Gesture',
    'Workspaces Outline',
    'Nephrology',
    'Important Devices',
    'Smart Outlet',
    'Tune',
    'Running With Errors',
    'Photo Camera',
    'Variables',
    'Diversity 2',
    'Flight Takeoff',
    'Web Stories',
    'Hdr Plus',
    'Sentiment Satisfied',
    'Sports Gymnastics',
    'Pergola',
    'Center Focus Weak',
    'Noise Aware',
    'Fence',
    'Prayer Times',
    'Home Repair Service',
    'Zone Person Alert',
    'Demography',
    'Precision Manufacturing',
    'Format Textdirection R To L',
    'Developer Board',
    'Feed',
    'North East',
    'Window',
    'Sports Kabaddi',
    'Pinch',
    'Front Hand',
    'Swipe Left',
    'Bookmark Added',
    'Logo Dev',
    '14mp',
    'Next Week',
    'Text Rotate Up',
    'Nfc',
    'Format Ink Highlighter',
    'Work',
    'Heat Pump',
    'Arrow Back',
    'Signal Wifi Bad',
    'Sync Saved Locally',
    'Rice Bowl',
    'Inventory',
    'Clear All',
    'Amend',
    'Person 2',
    'Money',
    'Format Align Center',
    'Moving Beds',
    'Settings Power',
    'Bluetooth',
    'Hls',
    'Battery Unknown',
    'Format Bold',
    'List',
    'Looks 4',
    'Android',
    'Settings Input Hdmi',
    'Propane',
    'Replay 30',
    'Arrow Back Ios',
    'Bluetooth Drive',
    'Sensor Occupied',
    'Wifi Calling',
    'Heart Plus',
    'Currency Bitcoin',
    'Looks 3',
    'No Photography',
    'Screen Lock Landscape',
    'Snowboarding',
    'Extension Off',
    'Keyboard Arrow Up',
    'Edit Attributes',
    'Browse Gallery',
    'Laptop Mac',
    'Hearing Disabled',
    'Battery Vert 050',
    'Inbox Customize',
    'Calendar View Week',
    'Manage History',
    'Downloading',
    'Nest Cam Stand',
    'Tools Pliers Wire Stripper',
    'Mp',
    'Crop Portrait',
    'Check Box',
    'Featured Play List',
    'Cloud',
    'Point Of Sale',
    'Menu',
    'Coffee',
    'Lab Profile',
    'Airline Seat Recline Normal',
    'Attribution',
    '30fps',
    'Mark As Unread',
    'Card Travel',
    'Call Missed Outgoing',
    'Temple Hindu',
    'Bedtime',
    'Headset Mic',
    'Ward',
    'Rotate Right',
    'Bento',
    'Network Wifi 1 Bar',
    'Cut',
    'Emergency Heat',
    'Price Check',
    'Border Style',
    'Merge Type',
    'Flowsheet',
    'Location Home',
    'Task',
    'Waves',
    'Hdr Strong',
    'Clear Night',
    'Campaign',
    'Arming Countdown',
    'History',
    'Video Stable',
    'Accessibility New',
    'Girl',
    'View Week',
    'Signal Cellular Connected No Internet 4 Bar',
    'Book',
    'Icecream',
    'Battery Charging 80',
    'Insert Chart',
    'South',
    'Nature People',
    'Queue Music',
    'Smart Button',
    'Satellite',
    'Person 3',
    'Table Bar',
    'Do Not Disturb Off',
    'Pause Circle',
    'Water Heater',
    'Add Moderator',
    'Not Accessible',
    'Local Parking',
    'Volume Up',
    'Iron',
    'Co Present',
    'Exposure Neg 2',
    'Airline Seat Flat',
    'Camera Indoor',
    'Commute',
    'Network Wifi 3 Bar',
    'Border Horizontal',
    'Sports Esports',
    'Mode Standby',
    'Compare',
    'Nest Found Savings',
    'Battery Vert 005',
    'Exposure Plus 2',
    'Attach File',
    'Bloodtype',
    '3g Mobiledata',
    'Train',
    'Av Timer',
    'Person 4',
    'Web Asset',
    'Video Label',
    'Volume Mute',
    'Assistant Navigation',
    'Free Cancellation',
    'Headphones Battery',
    'Preliminary',
    'Airwave',
    'Umbrella',
    'Arrow Circle Right',
    'Panorama',
    'Layers Clear',
    'Video Settings',
    'House',
    'Wallet',
    'Switch',
    'Mode Of Travel',
    'Currency Yuan',
    'Filter Alt Off',
    'Edit Off',
    'Sd Card Alert',
    'Blur Medium',
    'Diversity 3',
    'Strikethrough S',
    'Collections Bookmark',
    'Perm Phone Msg',
    'Emergency Home',
    'Call Made',
    'Contactless Off',
    'Padding',
    'Construction',
    'Hdr On',
    'Filter 9 Plus',
    'Beenhere',
    'Screen Search Desktop',
    'Superscript',
    'Gate',
    'Call End',
    'Brightness Medium',
    'Tour',
    'Battery Very Low',
    'Gif Box',
    'Autofps Select',
    'Door Sliding',
    'Diversity 4',
    'Avg Time',
    'Snooze',
    'Location Away',
    'Barcode Scanner',
    'Ballot',
    'Keyboard Control Key',
    'Currency Pound',
    'Museum',
    'Line End Diamond',
    'Order Approve',
    'Credit Score',
    'Apk Document',
    'Mfg Nest Yale Lock',
    '5mp',
    'Schedule Send',
    'South West',
    'Production Quantity Limits',
    'Sticky Note 2',
    'Egg Alt',
    'Update Disabled',
    'Cast Connected',
    'Document Scanner',
    'Speaker Notes',
    'Backspace',
    'Wallpaper',
    'Water Voc',
    'Hive',
    'Api',
    'Settings Night Sight',
    'Error Circle Rounded',
    'Auto Delete',
    'Filter List Off',
    'Mic External On',
    'Blur Short',
    'Wrap Text',
    'Baby Changing Station',
    'Texture',
    'Add Photo Alternate',
    'Snowing',
    'Invert Colors',
    '10mp',
    'File Download',
    'Functions',
    'Oncology',
    'Vertical Shades Closed',
    'Disc Full',
    'Watch',
    'Send Time Extension',
    'Width Normal',
    'Airplane Ticket',
    'Earbuds',
    'Open In Browser',
    'Nearby Error',
    'Swap Calls',
    'Clean Hands',
    'Keyboard Double Arrow Down',
    'Call Received',
    'Network Wifi 2 Bar',
    'Hourglass Empty',
    'Playlist Add Check Circle',
    'Content Paste Off',
    'Backup Table',
    'More Up',
    'Lens Blur',
    'Looks 5',
    'Laptop Chromebook',
    'Battery Low',
    'Imagesearch Roller',
    'Exit To App',
    'Switch Access Shortcut',
    'Text Rotation Angleup',
    'Open In New',
    'View Column 2',
    'Fluid Balance',
    'Workspace Premium',
    'Sip',
    'Preview',
    'Calendar Today',
    '3d Rotation',
    'Report',
    'Delete Sweep',
    'Safety Check',
    'More Horiz',
    'Sports Baseball',
    'Paragliding',
    'Fiber Smart Record',
    'Tools Ladder',
    'Motion Mode',
    'Circle',
    'Branding Watermark',
    'Dialpad',
    'Table Rows',
    'Flash On',
    'Photo Size Select Large',
    'Airware',
    'Filter 8',
    'Nest Cam Iq Outdoor',
    'Drive Folder Upload',
    'Altitude',
    'Motion Sensor Idle',
    'Phone Bluetooth Speaker',
    'Border Right',
    'Assignment Add',
    'Light',
    'Bathtub',
    'Crop 3 2',
    'History Toggle Off',
    'Add Call',
    'Voicemail',
    'Contrast',
    'Lan',
    'Cookie',
    'Faucet',
    'Sledding',
    'Battery Charging 50',
    'Square Foot',
    'Brush',
    'Timer 10 Alt 1',
    'Wifi Tethering Error',
    'Account Box',
    'Nest Cam Iq',
    'Account Balance Wallet',
    'Filter 1',
    'Phishing',
    'Healing',
    'Water Lux',
    'Person Pin Circle',
    'Euro',
    'Trip Origin',
    'Wash',
    'Call Merge',
    'Genetics',
    'Plumbing',
    'Copyright',
    'Specific Gravity',
    'Cast For Education',
    'Atr',
    'Videogame Asset Off',
    'Desktop Windows',
    'Nest Multi Room',
    'Arrow Selector Tool',
    'Nest Sunblock',
    'Upcoming',
    'Outbound',
    'Electric Car',
    'Lightbulb',
    'Male',
    'Home Speaker',
    'Power Rounded',
    'Filter 6',
    'Sound Detection Loud Sound',
    'Doorbell Chime',
    'Follow The Signs',
    'Display Settings',
    'Subtitles',
    'Water Ec',
    'Sentiment Neutral',
    'Format Size',
    'Upload File',
    'Flatware',
    'Trail Length',
    'Rocket',
    'Filter Alt',
    'Disabled Visible',
    'Developer Mode',
    'Attach Money',
    'Gastroenterology',
    'Nightlife',
    'Insert Page Break',
    'Outpatient Med',
    'Breakfast Dining',
    'Landscape',
    'Anchor',
    'Rsvp',
    'Signal Wifi 0 Bar',
    'No Luggage',
    'Dining',
    'Dataset Linked',
    'Energy Savings Leaf',
    'Heart Broken',
    'Fluid Med',
    'Video Call',
    'Waterfall Chart',
    'H Mobiledata',
    'Vertical Shades',
    'Change History',
    'Festival',
    'Nest Thermostat Zirconium Eu',
    'Grid 4x4',
    'Arrows More Down',
    'Light Group',
    'Navigate Before',
    'Power Settings New',
    'Replay',
    'Outdoor Garden',
    'Mobile Off',
    'Phone Iphone',
    'Grid View',
    'Floor Lamp',
    '8k Plus',
    'Format List Bulleted Add',
    'Vignette',
    'Keyboard Tab',
    'Format Strikethrough',
    'Find In Page',
    'Window Open',
    'Mic External Off',
    'Castle',
    'Text Rotation Down',
    'Build',
    'Image Search',
    'Broadcast On Personal',
    'Noise Control Off',
    'Add Link',
    'Communication',
    'Location Off',
    'Battery Vert 020',
    'Mode Cool',
    'Air Purifier Gen',
    'Airport Shuttle',
    'Rounded Corner',
    'Insert Text',
    'Alarm',
    'Accessible',
    'No Flash',
    'Play For Work',
    'Backpack',
    'Expand Circle Down',
    'Sports Soccer',
    'Javascript',
    'Filter',
    'Lab Research',
    'Zoom In',
    'Nest Wifi Mistral',
    'Article',
    'Filter 7',
    'Hand Bones',
    'Align Horizontal Center',
    'Medication',
    'Pin Drop',
    'Sports Football',
    'Tv Gen',
    'Margin',
    'Order Play',
    'Mark Email Unread',
    'Swipe Down Alt',
    'Priority',
    'Account Circle',
    'Local Mall',
    'Assistant Direction',
    'Wb Shade',
    'Snowmobile',
    'Pattern',
    'Airline Seat Legroom Extra',
    'Bungalow',
    'Sync',
    'West',
    'Maximize',
    'Event Busy',
    'Auto Read Play',
    'Event Available',
    'Date Range',
    'Money Off',
    '22mp',
    'Nest Detect',
    'Model Training',
    'Chip Extraction',
    'Detector Battery',
    'Filter 9',
    'Local Dining',
    'Install Mobile',
    'Line End',
    'Fullscreen',
    'Text Rotation Angledown',
    'Device Hub',
    'Urology',
    'Tonality',
    'Monitoring',
    'Gpp Bad',
    'Agender',
    'Battery Charging 60',
    'Warehouse',
    'Scene',
    'E911 Emergency',
    'Text Rotation None',
    'Personal Injury',
    'Detector Alarm',
    'Cancel Schedule Send',
    'Menu Book',
    'Youtube Searched For',
    'Edit Road',
    'Foggy',
    'Food Bank',
    'Radar',
    'Electric Rickshaw',
    'Donut Large',
    'Line Style',
    'Window Sensor',
    'Shield Moon',
    'No Accounts',
    'Near Me',
    'Barcode',
    'Wifi Password',
    'Support Agent',
    'Looks One',
    'Wifi Lock',
    'Notifications Off',
    'E911 Avatar',
    'Femur Alt',
    'Kitchen',
    'Recent Actors',
    'Ramp Left',
    'Center Focus Strong',
    'Multiple Stop',
    'Earbuds Battery',
    'Line Start Arrow Notch',
    'Nutrition',
    'Full Stacked Bar Chart',
    'Remove Done',
    'Cloud Off',
    'Restore From Trash',
    'Sync Alt',
    'Person Add Disabled',
    'Mood',
    'Backup',
    'Keyboard Backspace',
    'Pallet',
    'Computer',
    'Swipe Up Alt',
    'Ev Shadow',
    'Overview',
    'Call Missed',
    'Table Restaurant',
    'In Home Mode',
    'Assignment Turned In',
    'Attach File Add',
    'Crop 7 5',
    'E Mobiledata',
    'Dentistry',
    'Fiber Dvr',
    'Fast Forward',
    'Density Medium',
    'Dns',
    '1x Mobiledata',
    'Electrical Services',
    'Mode Off On',
    'Compost',
    'Local Taxi',
    'Record Voice Over',
    'Integration Instructions',
    'Switch Access Shortcut Add',
    'Docs Add On',
    'Line Start',
    'Camera Enhance',
    'Roller Shades',
    'Temp Preferences Custom',
    'Accessibility',
    'Cloudy Snowing',
    'Save',
    'Flip Camera Android',
    'Nest Tag',
    'Horizontal Rule',
    'Private Connectivity',
    'Sos',
    'Multicooker',
    'Adf Scanner',
    'Face 6',
    'Network Cell',
    'Energy Program Time Used',
    'All Inbox',
    'Qr Code',
    'Volunteer Activism',
    'Sprint',
    'Elevator',
    'Repeat On',
    'Apartment',
    'Female',
    'Format Paragraph',
    'Sound Detection Glass Break',
    'Send',
    'Quiet Time',
    'Timeline',
    'Nest Thermostat E Eu',
    'Garage',
    'Vaccines',
    'Scanner',
    'Crop Free',
    'Local Police',
    'Pages',
    'Airplanemode Inactive',
    'Rocket Launch',
    'Multiline Chart',
    'Check',
    'Album',
    'Media Link',
    'Energy Program Saving',
    'School',
    'Error',
    'Mosque',
    'Domain',
    'Data Saver On',
    'Local Bar',
    'Format Line Spacing',
    'Streetview',
    'Blender',
    '1k',
    'Toll',
    'Error Med',
    'Rebase',
    'Pool',
    'Width Full',
    'View Sidebar',
    'Exposure Zero',
    'Smart Toy',
    'Hdr Off',
    'Cyclone',
    'Perm Camera Mic',
    'Battery 50',
    'Interests',
    'Apps',
    '123',
    'Text To Speech',
    'Sentiment Extremely Dissatisfied',
    'Local Convenience Store',
    'Health And Safety',
    'Panorama Wide Angle',
    'Camera Outdoor',
    'Stacked Bar Chart',
    'Transform',
    'Bluetooth Disabled',
    'Kebab Dining',
    'Allergies',
    'Emoji Objects',
    'Pest Control Rodent',
    'Vertical Align Bottom',
    'Stairs',
    'Online Prediction',
    'Currency Lira',
    'Browse Activity',
    'Comments Disabled',
    'Family History',
    'Shopping Cart',
    'Camera Roll',
    'Event',
    'Emoji Food Beverage',
    'Screen Lock Rotation',
    'Format Image Left',
    'Slideshow',
    'Music Note',
    'Export Notes',
    'View Headline',
    'Confirmation Number',
    'Hourglass Top',
    'Arrow Upward',
    'Draw',
    'Settings Alert',
    'Devices Other',
    'Volcano',
    'More Vert',
    'Tag',
    'Vpn Key',
    'Minimize',
    'Connected Tv',
    'Ice Skating',
    'Remove Moderator',
    'File Upload Off',
    '8mp',
    'Circle Notifications',
    'No Meeting Room',
    'Thunderstorm',
    'Hub',
    'Nest Secure Alarm',
    'Area Chart',
    'Accessible Forward',
    'Mop',
    'Remember Me',
    'Humidity High',
    'Wifi Calling 2',
    'Data Object',
    'Aspect Ratio',
    'Request Quote',
    'Tips And Updates',
    'Present To All',
    'Front Loader',
    'Storm',
    'Arrow Left',
    'New Label',
    'Engineering',
    'Ramp Right',
    'Controller Gen',
    'Checklist Rtl',
    'Web Asset Off',
    'South East',
    'Panorama Vertical',
    'Auto Read Pause',
    'Wheelchair Pickup',
    'Prescriptions',
    'Transcribe',
    'Snowshoeing',
    'Skip Previous',
    'Dry Cleaning',
    'Trail Length Medium',
    '2mp',
    'Mixture Med',
    'Arrow Circle Left',
    'Nest Wake On Approach',
    'Emoji Transportation',
    'Photo',
    'Euro Symbol',
    'Wb Iridescent',
    'Apk Install',
    'Notifications',
    'Format H5',
    'Directions Bus',
    'Show Chart',
    'Delete Forever',
    'Restore Page',
    'Auto Awesome Mosaic',
    'Linear Scale',
    'Theater Comedy',
    'Colorize',
    'Login',
    'View Kanban',
    'Team Dashboard',
    'Battery Horiz 050',
    'Chrome Reader Mode',
    'Factory',
    'Punch Clock',
    'Contact Emergency',
    'Travel Explore',
    'Border All',
    'Signal Cellular Alt',
    'Electric Moped',
    'Format H2',
    '17mp',
    'Shuffle On',
    'Duo',
    'Subway',
    'Folder Off',
    'Cruelty Free',
    'Grouped Bar Chart',
    'Alarm Off',
    'Rotate Left',
    'Batch Prediction',
    'Sync Disabled',
    'North West',
    'View Carousel',
    'Check Small',
    'Next Plan',
    'Flare',
    'First Page',
    'Calendar Month',
    'Chalet',
    '6mp',
    'Closed Caption Disabled',
    '2k',
    'Smart Display',
    'Data Exploration',
    'Sync Lock',
    'Low Priority',
    'Autopay',
    'View Day',
    'Assignment Return',
    'Ads Click',
    'No Meals',
    'Widgets',
    'Border Inner',
    '13mp',
    'Masks',
    'Motion Photos Off',
    'Settings Panorama',
    'Detector Offline',
    'Stadia Controller',
    'Airlines',
    'Assured Workload',
    'Place Item',
    'Airline Stops',
    'Deck',
    'Phonelink Setup',
    'Psychology Alt',
    'Table View',
    'Timer Off',
    'Face Retouching Off',
    'Arrows More Up',
    'Add Notes',
    'Transgender',
    'Keyboard',
    'Forms Add On',
    'Flight Land',
    'Astrophotography Auto',
    'Turn Sharp Right',
    'Sports Motorsports',
    'Package',
    'Library Add Check',
    'Forward',
    'Cake',
    'Edit Notifications',
    'Policy',
    'Line Weight',
    'Quiet Time Active',
    'Nest Wake On Press',
    'Barefoot',
    'Palette',
    'Help',
    'Signal Wifi 4 Bar',
    'Local Post Office',
    'Sprinkler',
    'Location Chip',
    'Bring Your Own Ip',
    'Looks Two',
    'Social Distance',
    'View In Ar New',
    'Question Mark',
    'Request Page',
    'Emoji Flags',
    'Upload',
    'Format List Numbered Rtl',
    'Dock',
    'Signal Cellular Off',
    'Battery 60',
    'Broadcast On Home',
    'Person Filled',
    'Woman',
    'Offline Pin',
    'Add To Photos',
    'Holiday Village',
    'Keyboard Arrow Right',
    'Cell Wifi',
    'Co2',
    '19mp',
    'Rotate 90 Degrees Ccw',
    'Heart Minus',
    'Sports Basketball',
    'Analytics',
    'Stop Screen Share',
    'View Agenda',
    'Door Open',
    'Directions Railway',
    'Humidity Percentage',
    'Nights Stay',
    'Move To Inbox',
    'Line Start Arrow',
    'Format H3',
    'Open With',
    'Pending',
    'Stethoscope Arrow',
    'Hiking',
    'Water Orp',
    'Add To Drive',
    'Home Pin',
    'Productivity',
    'Shopping Basket',
    'Approval',
    'Devices',
    'Moving Ministry',
    'Battery Alert',
    'Temple Buddhist',
    'Checklist',
    'Block',
    'Motion Photos Auto',
    'Send To Mobile',
    'Store',
    'Arrow Back Ios New',
    'Vpn Key Off',
    'Person Pin',
    'Account Balance',
    'Add Task',
    'Yard',
    'Query Stats',
    'Notification Add',
    'Kitesurfing',
    'Reviews',
    'Crib',
    'Art Track',
    'Format H4',
    'Battery Full Alt',
    'Screenshot Monitor',
    'Linked Camera',
    'Wifi Calling 3',
    'Align Vertical Bottom',
    'Chair Alt',
    'Swap Horizontal Circle',
    'Arrow Right',
    'Detector Co',
    'Medication Liquid',
    'Bedroom Parent',
    'Home Iot Device',
    'Device Thermostat',
    'Priority High',
    'Share',
    'House With Shield',
    'Gif',
    'Early On',
    'Comment Bank',
    'Skip Next',
    'Notifications Active',
    'Battery Profile',
    'Phonelink Lock',
    'Blur On',
    'Badge',
    'Format Image Right',
    'Call Split',
    '8k',
    'Car Repair',
    'Chevron Right',
    'Other Houses',
    'Open In New Off',
    'Vaping Rooms',
    'Local Hospital',
    'Ad Units',
    'Shield With Heart',
    'Fitness Center',
    'Ssid Chart',
    'Dvr',
    'All Out',
    'Diagnosis',
    'Swipe Right Alt',
    'Currency Yen',
    'Location On',
    'Router',
    'View Compact'
  },
);
